### ISSUE TITLE
I wish it was under MIT License & Wonder why it isn't! :(

### ISSUE THREAD

**Issue by howardroark2018** [mozilla/togetherjs#1088]
Hello, 
I just happened to check for the license of this code, which I had been planning to use for my own projects, and I just realized that my pre-conception of taking an MIT license for granted when using mozilla's web based applications / components / code  turned out to be wrong. 
Well, Considering that other similar **awesome web projects like PopCorn.js project built by Mozilla team were licensed as MIT which, to my understanding made it much more attractive to developers, who would want to implement some of the code in their own projects.** Again considering **Mozilla's honest and wonderful motive of helping the modern web move forward and thereby making the web stand on a set of modern & universal web standards;** I believe that the MIT license would have had been the best way to do it. Had the code been server side, then, an MPL would have been equally good. But the project is actually client side, which makes the whole deal of MPL licensing much more restrictive compared to MIT.  **And come-on, the core of this project (Which itself is awesome) rests upon JavaScript & WebRTC, both of which are under the wonderful MIT License.** SO, why not follow the same license, instead of adopting the comparitively-more-restrictive licenses like the MPL?  Well, it might not be such a big deal to you guys;  Just that, **I am sad, that many developers including me would have to forget about using together.js in our own proprietary larger works, by dynamically linking the code to our own projects (without the trouble of going through complex license terms & releasing their own source codes just because they used a bit of MPL code in their larger project.)**

Nevertheless, it's a great work & I have always been a fan of you guys! 

Thanks a lot for making the web as beautiful as it is today. Web without mozilla would have been crap in a lot of ways! Thank God, The World has Mozilla!! :)

**-Anime.sh**

**Comment by gerv** [comment]
Hi sheaffer,

My name's Gerv; I'm the first point of contact for licensing stuff at Mozilla. Mozilla uses a variety of licenses for its code, both web-based and not. We don't believe that one license is unilaterally "more attractive to developers" - it depends on what the code is, and which developers you are asking, and also on our licensing goals. And when we do choose a permissive license, we like to choose the Apache license 2.0, because we think everyone should be using modern open source licenses with patent clauses for any non-trivial work.

together.js is under the MPL, which is designed to allow the use of the code in proprietary works. You are required to provide source of any MPL bits to anyone you give binaries to, but you are not required to provide source of non-MPL bits. Hence Netscape, if you can remember that far back, built a browser based on the Mozilla browser codebase, but with e.g. a proprietary skin and services.

Using any code (open source or proprietary) requires understanding and respecting its license, and Mozilla's code is no exception. We are happy to help you with any parts of the MPL which may be unclear. We do also have a FAQ: https://www.mozilla.org/en-US/MPL/2.0/FAQ/ . Qs 9 and 10 might be most relevant to you.

With best wishes,

Gerv

**Comment by wcaaan** [comment]
@gerv Can you please explain in simple word, Can i use togetherjs code for my own project or not ? and if i can do i have to contribute or what ?

**Comment by gerv** [comment]
@mwgi2005: if it were possible to explain everything in a couple of sentences, the license would only be a couple of sentences long. You can't take my explanations as a substitute for reading and understanding the license.

You can use together.js for whatever you want as long as you respect the terms of the license. There are various documents out there, some linked above, to help explain those terms to you.

**Comment by wcaaan** [comment]
OK, Thank you
