### ISSUE TITLE
How can we restart / expand TogetherJS development?

### ISSUE THREAD

**Issue by ianb** [mozilla/togetherjs#1127]
I haven't been paying attention to TogetherJS at all, I'm afraid. But despite that, I'd like the project to become its best self. (And also feel less guilty about it.)

I thought I'd start this issue to consider what might be helpful.  Some ideas:

- Move the togetherjs.com domain name to point to GitHub, so the "deployment" can be handled entirely through GitHub pages. Maybe just redirect the domain to togetherjs.github.io ? (Otherwise I'm not sure if we can use https, though I guess we could [with CloudFlare](https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b) – but that's more infrastructure)
- Move togetherjs to its own GitHub organization?
- Is there some communication channel we can use to attract attention to the project and encourage contribution? TogetherJS itself?

**Comment by raiyankamal** [comment]
Hi @ianb , 
I've been watching togetherjs for a while now and would really love to see togetherjs evolve further.
In the past, I've found myself following links to open source projects posted on reddit. A few times I actually decided to stick around and edit a line of code or two. I don't know how other users feel about reddit, but this is definitely a channel worth considering.

**Comment by FlyingJester** [comment]
I would love to see TogetherJS continued as well! I've used it for a few just-for-fun demos, and it's surprising it hasn't seen more use.

**Comment by piotr-dobrogost** [comment]
I think I missed when and why it was stopped in the first place?

**Comment by hpvd** [comment]
could someone describe the actual status of this this tool?
like this:
- working great only tiny things are missing
- already useful but some annoying problems
- not usefull at all because its only a good idea at this state

**Comment by hpvd** [comment]
does someone use it in "real world" on daily basis?

**Comment by FlyingJester** [comment]
I can share my experiences with it. I had a project that I used it in:

https://github.com/FlyingJester/LandGrab

I never finished the project, but it demonstrated TogetherJS working properly. You could invite someone to 'play' with you, you could roll the dice and they would see the result. At the time that I wrote that, it functioned properly.

One note I have about TogetherJS right now is that it seems something broke between when I last touched that (August 2015) and now. Configuration in particular seems to no longer function correctly, and examining what's happening in the developer console shows that none of my configuration works properly anymore (it's still correct according to the docs).

I'm beginning a new project that will use TogetherJS, but due to what happened to LandGrab, I'm going to host the server components on my own hardware, and use an older version of the both the server components and the client script (from around when I'm sure LandGrab functioned properly). I have confidence in the software, but less so in provided infrastructure at this point.

I would be curious to hear any status update from the TogetherJS developers.

**Comment by ianb** [comment]
Mozilla is no longer sponsoring TogetherJS development. It was a Mozilla Labs project, and Mozilla Labs closed down a long time ago. (I wrote about it some [here](http://www.ianbicking.org/blog/2014/09/professional-transitions.html).)

So if TogetherJS has a future, it will have to be from support from outside Mozilla. We do host the infrastructure, and that's probably fine indefinitely, but it's not easy to get changes made as a result.

@woniesong92 has been doing some maintenance (much appreciated!), and I think has access to add committers to the repo and whatnot, but there may be holes in what he can do.

**Comment by oskarkrawczyk** [comment]
Hey all, this is Oskar from @jsfiddle

We're heavy users of TogetherJS (we call it `Collaboration`). In 2017 there were more than 800k TogetherJS sessions started – this is in the top 15 actions on JSFiddle (that we track).

While the library works well enough, I confirm that some configuration options are no longer functioning correctly.

This is a wonderful piece of coding and would be sad if was forgotten to the point of not working, which is why I'd like to suggest some help from our end.

While there's not much we can contribute in form of code, we could become a sponsor on Patreon for an individual or a team/organization (as @ianb suggested) who could fix current issues and maintain the library.

**Comment by zscally** [comment]
I use TogetherJS as a collaboration component as well, as I do not know the adoption of the feature on our site, I do like the idea of the abilities it bring to the table right out of the box. It would be awesome if we could form some sort of road map on what we should do to bring the current code base up to-date and possible features we would like to see. One thing I think is prevent is that the voice and chat features are a little lacking.

**Comment by grahamperrin** [comment]
> … attract attention to the project …

I learnt of the project accidentally via the [Browse Together](https://addons.mozilla.org/addon/browse-together/) extension for Firefox, which was listed in [Latest on AMO](https://addons.mozilla.org/addon/latest-on-amo/). **The name** caught my eye, 

> Browse Together

I tried the extension for the first time, then visited https://togetherjs.com/ … very interesting :+1: 

Seeking _extension_ in this repo led me to https://github.com/mozilla/togetherjs/issues/1115#issuecomment-303045328 and the earlier extension by @Mte90, [TogetherJS Companion](https://addons.mozilla.org/addon/togetherjs-companion/).

**Comment by rugk** [comment]
AFAIK Mozilla wanted to reopen Mozilla Labs. What is the current status of this? Also JSFiddle just integrated TogetherJS into their system…

And what do browser extensions have to do with that?

**Comment by oskarkrawczyk** [comment]
> Also JSFiddle just integrated TogetherJS into their system…

Many years ago not "just" :-)

**Comment by rugk** [comment]
Oh yeah, 2013. Sorry… :laughing: (found an old news article)

**Comment by joeyguerra** [comment]
@ianb any update on this? what are the options? passing ownership to someone else?

**Comment by oskarkrawczyk** [comment]
Hey @ianb, I was wondering if you even had a chance to think more about splitting this into a separate organization?

That might be a good step forward to sponsoring the org and perhaps find some people willing to contribute.

@jsfiddle is still open to sponsoring future development of this project.

**Comment by Denoder** [comment]
I'd be more than willing to help contribute. I currently utilizing this myself, recently re-enabled movable docks: ( deciding if i should have it save the position per session or browser-wide )
![](https://i.imgur.com/AMTVQf0.gif)

Also added synchronizing video timeupdates/play/pause - i made it work for video players other than a plain video element so you would be able to do this for jwplayer, flowplayer, videojs, etc. Adapted some of the pull-requests that werent merged and some of them do work well.

Trying to optimize the code because sometimes when reloading the order in which the modules load would generate an error, so if anyone has any pointers.

**Comment by Denoder** [comment]
Ive also recently managed to get 1 on 1 voice chat to work. I have not tested it with multiple people, but with 1 on 1 ive been able to confirm it from my phone's mic -> my computer's mic and vice versa.

**Comment by simondiep** [comment]
@ianb I completely agree with your suggestions.  What do you need from us to get the ball rolling?  It sounds like the jsfiddle org would be an option.

**Comment by Denoder** [comment]
So is no one willing to help work on this?

**Comment by AlaskanEmily** [comment]
I have interest in this and have used TogetherJS before, but it seems like the things I would want it for are not what other people do. I really have no interest in things like video synchronization or sharing microphones or audio, my main use case is for HTML5 networked games. I don't even want the default dock.

**Comment by lmelon** [comment]
Hi, I am potentially interested in helping maintaining a fork of this project.
There is very limited (if any) open-source alternative. So I guess there is a clear need.

Happy to discuss.

**Comment by dr-hc-solo** [comment]
HI, i'd also love to see the lib revived. I integrated it in a small private project and it's pretty nice. I also reactivated moving the dock. It could stick to each side (lrtb) now and the position will be saved in local storage. I also fixed some pointer issues if having svg on the page. And updated the code to the RTC inferface changes. Sadly audio doesn't work for me without a proper TURN server.
I'd like to share my code.

**Comment by rugk** [comment]
> I'd like to share my code.

You may already upload it on GitHub or so, so people can later find and use it, in case they need it.

**Comment by dr-hc-solo** [comment]
I did so.
Forked and committed to different feature branches. Also initiated some pull request..

**Comment by oskarkrawczyk** [comment]
Hi all, since it would seem like the project has been officially shut down, we've decided to fork it into the @jsfiddle organization and try and keep it alive:

→ **https://github.com/jsfiddle/togetherjs**

At the moment the official hub server (http://hub.togetherjs.com/) that's responsible for TogetherJS to work, is offline so not much is functional.

I'll be trying to get a new public hub server up and running in the coming days.

For the moment the packages are so outdated they don't even finish a `npm install` – I'll be working on that.

If anyone is up for helping out with maintaining or getting the hub up and running, please do let me know! 🤙🏻

**Comment by dr-hc-solo** [comment]
Thanks for the info.
I wondered why i can't connect to the hub just yesterday.
Shall i move my pull requests for the fixes i made to your fork?

**Comment by oskarkrawczyk** [comment]
@dr-hc-solo Sure, I'll merge in the PR's as soon as we manage to get the hub server running.

**Comment by OpenHypervideo** [comment]
Thanks for the commitment @oskarkrawczyk ! That would be great! I guess it was about time someone takes this on.

**Comment by culmat** [comment]
Hi Oskar,
I am getting 404 for https://github.com/jsfiddle/togetherjs  - is this a private repo?
Regards,
Matthias

**Comment by dr-hc-solo** [comment]
I ran the hub server locally yesterday like they describe on https://togetherjs.com/docs/#hosting-the-hub-server. I checked basic functionality like connecting two peers. I looked like it worked. I could see the cursors moving around at least..

**Comment by OpenHypervideo** [comment]
Did you have any luck setting it up on a live server with SSL working? In the docs it looks like you have to set up an additional proxy. My Node skills are very limited unfortunately. But if there's a few bulletproof steps we can try to set up our own servers until there is a public hub server again.

**Comment by oskarkrawczyk** [comment]
I'm in the middle of setting up the hub server. It's not super easy to get it all done on DigitalOcean.

It's going to be available at http://hub.jsfiddle.net, at last for now.

**Comment by dr-hc-solo** [comment]
@oskarkrawczyk any good news yet?
Pinging http://hub.jsfiddle.net already works

**Comment by OpenHypervideo** [comment]
Hi @oskarkrawczyk, the server seems reachable but currently shows the TogetherJS source. Any idea whether or not it will be possible to run & use the server? Can @ianb or someone else from the former Mozilla team help set this up?

**Comment by oskarkrawczyk** [comment]
Please see this ticket for details on the server https://github.com/jsfiddle/togetherjs/issues/1172

**Comment by OpenHypervideo** [comment]
> Please see this ticket for details on the server #1172

Sorry I didn't see that before. Thank you!

**Comment by pratik9722** [comment]
Audio chat is not working anyone has an idea how to fix this??
